.travis.yml

- It will notify build status to #baker-build slack channel. 
- Also, emails to the individual commiter if a build fails or build status changes.

Added slack integration to notify build status 

---

core/src/main/resources/reference.conf

in case when used as ingredients they do not fallback to JavaSerializer

adding kryo serialization mappings for java standard wrapper types

---

CHANGELOG.md
compiler/src/main/scala/com/ing/baker/compiler/package.scala
intermediate-language/src/main/scala/com/ing/baker/il/package.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/common/Interaction.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/common/InteractionFailureStrategy.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/common/package.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/InteractionFailureStrategy.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/Recipe.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/package.scala
recipe-dsl/src/main/scala/com/ing/baker/recipe/scaladsl/InteractionDescriptor.scala
recipe-dsl/src/test/java/com/ing/baker/recipe/javadsl/RecipeTest.java
recipe-dsl/src/test/scala/com/ing/baker/recipe/common/InteractionFailureStrategySpec.scala
test-module/src/test/scala/com/ing/baker/compiler/RecipeCompilerSpec.scala
test-module/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala

Now you configure a boolean if you want one and a default one is created.
Its not possible to set your own custom events anymore.
This makes it possible to use this as the defaultRetryStrategy on the recipe.
In the old solution they would get the same event that would only fire is all interactions retry exhaust.

changed the way RetryExhaustedEvents are set.

---

runtime/src/main/protobuf/common.proto
runtime/src/main/scala/com/ing/baker/runtime/actor/process_index/ProcessIndex.scala
runtime/src/main/scala/com/ing/baker/runtime/actor/process_instance/ProcessInstance.scala
runtime/src/main/scala/com/ing/baker/runtime/actor/serialization/ProtoEventAdapter.scala
runtime/src/main/scala/com/ing/baker/runtime/core/Baker.scala
runtime/src/main/scala/com/ing/baker/runtime/core/ProcessState.scala
runtime/src/main/scala/com/ing/baker/runtime/core/interations/MethodInteractionImplementation.scala
runtime/src/main/scala/com/ing/baker/runtime/java_api/JBaker.scala
runtime/src/main/scala/com/ing/baker/runtime/petrinet/RecipeRuntime.scala
runtime/src/test/scala/com/ing/baker/runtime/actor/process_index/ProcessIndexSpec.scala
runtime/src/test/scala/com/ing/baker/runtime/actor/serialization/BakerProtobufSerializerSpec.scala
test-module/src/test/java/com/ing/baker/JBakerTest.java
test-module/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala

Allows to use GetEventNameList to get the events directly from the ProcessInstance instead of using Akka query .
This is more optimized if you are only interested in the names of the events instead of their contents.

Event name list

---

README.md

The link to `ExampleSpec` from the main project's README was broken

Fix broken ExampleSpec link in README

---

compiler/src/main/scala/com/ing/baker/compiler/RecipeCompiler.scala
intermediate-language/src/main/scala/com/ing/baker/il/RecipeVisualizer.scala
intermediate-language/src/main/scala/com/ing/baker/il/dot/PetriNetDot.scala
intermediate-language/src/main/scala/com/ing/baker/il/petrinet/Place.scala
petrinet-api/src/main/scala/com/ing/baker/petrinet/api/package.scala
recipe-dsl/src/test/scala/com/ing/baker/recipe/TestRecipe.scala
runtime/src/test/scala/com/ing/baker/BakerRuntimeTestBase.scala
runtime/src/test/scala/com/ing/baker/il/RecipeVisualizerSpec.scala
runtime/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala

Changed the way input places work for events.
Now one shared input place is created for each event.
Interactions that fire events now are linked via a new Intermediate transition to the event.
This way the incoming lines from interactions towards an Event work like an OR instead of an AND.
Also rewrote the compactNode of the recipe visualiser so that it can compact transitions correctly and not only places.
This closes #42

Make event input works as OR instead of AND

---

intermediate-language/src/main/scala/com/ing/baker/il/RecipeVisualizer.scala

This removes the intermediate small circle node for intermediate transitions the recipe graph

Do not visualize multi facilitator transitions

---

README.md

I suggest we also add it to the top of github.
You can specify specify a website next to the title.

Add link to documentation to the readme

---

docs/documentation/process-execution.md
docs/documentation/recipe-dsl.md
runtime/src/main/scala/com/ing/baker/runtime/actor/process_index/ProcessIndex.scala
runtime/src/main/scala/com/ing/baker/runtime/core/Baker.scala
runtime/src/main/scala/com/ing/baker/runtime/java_api/JBaker.scala

Event / ingredient renames where not taken into account in the *resolveInteraction* feature from `2.0.3`

Fix a bug relating to event renames and overriding interaction output

---

project/Dependencies.scala

issue:
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.typelevel:cats-core_2.12:1.1.0 paths to dependency are:
+-com.ing.currentaccounts:pCurrentAccountOpenJointAPI-Recipe:00.00.01.003-SNAPSHOT
+-com.ing.baker:baker-runtime_2.12:2.0.5
+-org.typelevel:cats-core_2.12:1.1.0
and
+-com.ing.currentaccounts:pCurrentAccountOpenJointAPI-Recipe:00.00.01.003-SNAPSHOT
+-com.ing.baker:baker-runtime_2.12:2.0.5
+-org.typelevel:cats-effect_2.12:0.10
+-org.typelevel:cats-core_2.12:1.0.1
```
fix: 
- Use a new version of cats-effect.
- Use the cats-core version that matches the cats-effect version.

Fix dependency convergence mismatch

---

docs/sections/versions/baker-3-release-notes.md

Based on an explanation by @Tim-Linschoten:
https://github.com/ing-bank/baker/issues/287#issuecomment-542261760

docs: document RuntimeEvent access removal in v3

---

project/Dependencies.scala
runtime/src/main/scala/com/ing/baker/runtime/akka/internal/RecipeRuntime.scala

Updates org.typelevel:cats-effect from 1.4.0 to 2.0.0.
Release Notes/Changelog

Update cats-effect to 2.0.0

---

baas-node-state/src/main/scala/com/ing/baker/baas/state/Main.scala
baas-node-state/src/main/scala/com/ing/baker/baas/state/ServiceDiscovery.scala
baas-node-state/src/test/resources/mocks/kubeapi_GET_services_watch_event.json
baas-node-state/src/test/scala/com/ing/baker/baas/kubeapi/Services.scala
baas-node-state/src/test/scala/com/ing/baker/baas/mocks/KubeApiServer.scala
baas-node-state/src/test/scala/com/ing/baker/baas/state/StateNodeSpec.scala
baas-smoke-tests/src/test/scala/com/ing/baker/baas/smoke/BakeryFunSpec.scala
build.sbt
project/Dependencies.scala
runtime/src/test/scala/com/ing/baker/runtime/akka/BakerInquireSpec.scala

1. Removed the java api library in favor of Skuber
2. The ServiceDiscovery.scala in the state node project now uses an akka stream to update local cache
3. The constructor (ServiceDiscovery.resource) still uses cats.effect.Resource to create and cleanup the stream
4. There is an improvement on the functional tests, liveness checks for the discovery of the services were added before each test (on the StateNodeSpec.contextBuilder function)

Skuber and watch for service discovery

---

azure.yaml
build.sbt
project/Publish.scala
project/build.properties
project/plugins.sbt
set-version.sh
version.sbt

- Azure pipeline to build OS Baker(y)
- aether plugin since default sbt deploy doesn't work with Azure
- Publish to either Sonatype or Azure feed (injected via env vars)
- Resolver cache
- CI/CD-friendly versioning (no -SNAPSHOTs anymore)
Unrelated:
- sbt version bump

azure pipeline OS build

---

bakery-integration-tests/src/test/scala/com/ing/bakery/smoke/BakeryConfigMapSmokeTests.scala
bakery-integration-tests/src/test/scala/com/ing/bakery/smoke/BakeryCrdSmokeTests.scala

Sorted the event comparison of the Bakery integration tests because event order is not deterministic.

Sorted the event comparison of the Bakery integration tests

---

core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/internal/RecipeRuntime.scala

Fixed the order of input ingredients used to call interactions. This is important since predefined ingredients should take precedence over state ingreidents.

Fixed the order of input ingredients used to call interactions.

---

azure-build.yaml
bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverState.scala
bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverUtils.scala
bakery/baker-client/src/main/scala/com/ing/bakery/javadsl/BakerClient.scala
bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala
bakery/baker-client/src/test/scala/com/ing/bakery/client/BakerClientSpec.scala
bakery/baker-client/src/test/scala/com/ing/bakery/common/FailoverStateSpec.scala
bakery/baker/src/main/scala/com/ing/bakery/baker/ServiceDiscovery.scala
bakery/baker/src/test/scala/com/ing/bakery/baker/BakerNodeSpec.scala
bakery/controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/ControllerOperations.scala
build.sbt
examples/bakery-client-example/src/main/scala/webshop/webservice/Main.scala
project/BuildInteractionDockerImageSBTPlugin.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt

- several version bumps of deps
- default JDK11 build
- /api/bakery prefix is configurable now in the client

bundled dependency version bump + configurable API client URL

---

build.sbt
project/Dependencies.scala

- Added akka pki library explicitly, since it's implicitly added by the akka management library, but from there it's not the same version as the other akka libraries.
- ~~Excluded normal bcprov dependencies from bakery-state, because different bcprov version is used by skuber, which conflicts with the standard bcprov dependencies.~~ Updated version of skuber to 2.6.4.
These changes help reduce the number of classpath issues you need to solve to use bakery-state.

Fix classpath issues of bakery-state

---

core/akka-runtime/src/main/resources/reference.conf
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/BakerActorProvider.scala
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/ClusterBakerActorProvider.scala
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/LocalBakerActorProvider.scala
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala
core/akka-runtime/src/test/java/com/ing/baker/BakerTest.java

If a Persistent Actor has any persistence error it will be stopped and not restarted. To ensure the ProcessIndex and ProcessInstance are restarted if there are hickups against Cassandra a BackoffSupervisor needs to be configured.

BackoffSupervisor for ProcessIndex & ProcessInstance

---

bakery/interaction/src/main/scala/com/ing/bakery/interaction/RemoteInteractionService.scala

collectionAsScalaIterable is deprecated and should be replaced by collectionAsScalalterableConverter

Updated collectionAsScalalterableConverter

---

core/baker-test/src/main/scala/com/ing/baker/test/RecipeAssert.scala
core/baker-test/src/test/java/com/ing/baker/test/javadsl/RecipeAssertTest.java

While using `baker-test` for testing we have noticed that if the baker recipe instance does not exist anymore while calling `assert` or `log` or `waitFor` using `BakerAssert` - you stuck in a loop and get `StackOverflowException`.
With this fix instead of `StackOverflowException` you get the original `NoSuchProcessException` which makes much more sense.

Fix StackOverflowException in baker test

---

core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/BakerExecutionSpec.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/common/Baker.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/model/BakerF.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/BakeRequest.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/JsonDecoders.scala
core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/JsonEncoders.scala
core/baker-interface/src/test/scala/com/ing/baker/runtime/serialization/JsonDecodersSpec.scala
core/baker-interface/src/test/scala/com/ing/baker/runtime/serialization/JsonEncodersSpec.scala
http/baker-http-client/src/main/scala/com/ing/baker/http/client/scaladsl/BakerClient.scala
http/baker-http-server/src/main/scala/com/ing/baker/http/server/javadsl/BakerWithHttpResponse.scala
version.sbt

For some implementations this can be more optimal then doing them separate.

Allows the adding of metadata on the bake itself. 

---

examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeWithEventTransformation.java
http/baker-http-dashboard/package.json

Fixed the output ingredient rename in Java. In the example it was renaming input ingredients

Fixed output ingredient rename example/doc for Java

---

core/baker-interface-kotlin/src/main/kotlin/com/ing/baker/runtime/kotlindsl/FunctionInteractionInstance.kt
core/baker-interface-kotlin/src/test/kotlin/FunctionInteractionInstanceTest.kt
core/recipe-dsl-kotlin/src/main/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDsl.kt

Kotlin DSL using createType().javaType on reified generic instance sometimes fail, replaced with typeOf<...>() function which was created for this specific scenario.
Additionally added a test for the functionInteractionInstance() utility method, removed reified keyword where not needed.

Kotlin DSL patch

---

core/baker-interface-kotlin/src/main/kotlin/com/ing/baker/runtime/kotlindsl/FunctionInteractionInstance.kt
core/baker-interface-kotlin/src/test/kotlin/FunctionInteractionInstanceTest.kt
core/recipe-dsl-kotlin/src/main/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDsl.kt
core/recipe-dsl-kotlin/src/test/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDslTest.kt

Bug surfaced when declaring recipe ingredients or functioninteractioninstances using the Kotlin DSL that contained optionals, but chances are all generic wrappers are affected. Patch to resolve this.

Type handling in Kotlin DSL still had a bug

---

.github/workflows/ci.yml

This pull request refactors the CI workflow to add a conditional step for generating draft release notes. The step will only run for pushes to the master branch or for tags starting with 'v'. This ensures that draft release notes are only prepared when necessary, reducing unnecessary processing and improving efficiency.

Refactor CI workflow to add conditional step for draft release notes

---

bakery/state/src/main/scala/com/ing/bakery/AkkaBakery.scala
bakery/state/src/main/scala/com/ing/bakery/ClosableBakery.scala
core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
http/baker-http-server/src/main/scala/com/ing/baker/http/server/scaladsl/Http4sBakerServer.scala

Exposes the AkkaBaker config to allow for use of this in the dashboards.
Expose some shared vals & methods in the Http4sBakerServer to allow for re-use them in other places.

Exposes methods/functions to allow for re-use.

---

http/baker-http-server/src/main/scala/com/ing/baker/http/server/javadsl/BakerWithHttpResponse.scala

Made the 3 bake methods on the BakerWithHttpResponse have different names so they can be easier used in Java/Kotlin.

Rename the 3 bake methods on the BakerWithHttpResponse have different names

---

.github/workflows/ci.yml

Restrict Azure publishing to push events and pull requests originating from the main repository, excluding tags. This ensures workflows do not run for pull requests from forked repositories.

Update Azure publish conditions in CI workflow
