build.sbt, project/Dependencies.scala
Cleaned up warnings when importing the project in IntelliJ and treating warnings as errors.
=> Cleanup warnings

core/src/main/scala/com/ing/baker/compiler/CompiledRecipe.scala, core/src/main/scala/com/ing/baker/compiler/Recipe.scala, core/src/main/scala/com/ing/baker/java_api/JRecipe.scala, core/src/main/scala/com/ing/baker/scala_api/SRecipe.scala, core/src/test/scala/com/ing/baker/compiler/RecipeCompilerSpec.scala, core/src/test/scala/com/ing/baker/core/EventRecoverySpec.scala
* Updates events definition in Recipe, JRecipe and SRecipe
* Updates existing code to comply to new requirement for events
* Removes validation test that became irrelevant
=> Updates definition of events so its elements extend from Event

build.sbt, intermediate-language/src/main/scala/com/ing/baker/il/package.scala, intermediate-language/src/main/scala/com/ing/baker/il/petrinet/package.scala, project/Dependencies.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/ActorIndex.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/KryoSerializer.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/ShardedActorProvider.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/Util.scala, runtime/src/main/scala/com/ing/baker/runtime/core/Baker.scala, runtime/src/main/scala/com/ing/baker/runtime/core/EventListener.scala, runtime/src/main/scala/com/ing/baker/runtime/java_api/JBaker.scala, runtime/src/main/scala/com/ing/baker/runtime/petrinet/TaskProvider.scala, test-module/src/test/scala/com/ing/baker/runtime/actor/ActorIndexSpec.scala, test-module/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala
- Do not merge yet, depends on a release of kagera 0.2.24
Events are received for processes on the local JVM only and at most once.
=> Adds an event stream to Baker.

intermediate-language/src/main/scala/com/ing/baker/il/RecipeValidations.scala, test-module/src/test/scala/com/ing/baker/compiler/RecipeCompilerSpec.scala, test-module/src/test/scala/com/ing/baker/recipe/scaladsl/ScaladslSpec.scala, test-module/src/test/scala/curryonexample/newCustomerRecipeScala.scala
=> validate that ingredients are not of primitive type after compilation

README.md
A few minor issues with README.md file, the most important one being the "%%" issue in the sbt dependencies. 
Cheers!
=> Minor issues with README.md file

baas/src/main/scala/com/ing/baker/recipe/commonserialize/InteractionDescriptor.scala, compiler/src/main/scala/com/ing/baker/compiler/RecipeCompiler.scala, recipe-dsl/src/main/scala/com/ing/baker/recipe/common/InteractionDescriptor.scala, recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/InteractionDescriptor.scala, recipe-dsl/src/main/scala/com/ing/baker/recipe/scaladsl/InteractionDescriptor.scala, recipe-dsl/src/test/java/com/ing/baker/recipe/javadsl/InteractionDescriptorTest.java, recipe-dsl/src/test/scala/com/ing/baker/recipe/scaladsl/InteractionDescriptorSpec.scala, test-module/src/test/scala/com/ing/baker/TestRecipeHelper.scala, test-module/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala
Its now possible to have multiple OR conditions on the same interaction.
=> Or conditionals fix in interaction

bakertypes/src/main/scala/com/ing/baker/types/Converters.scala, bakertypes/src/main/scala/com/ing/baker/types/Value.scala, bakertypes/src/test/scala/com/ing/baker/types/ConvertersSpec.scala, recipe-dsl/src/main/scala/com/ing/baker/recipe/scaladsl/package.scala, runtime/src/main/protobuf/common.proto, runtime/src/main/scala/com/ing/baker/runtime/actor/serialization/ProtoEventAdapter.scala, test-module/src/test/scala/com/ing/baker/AllTypeRecipe.scala, test-module/src/test/scala/com/ing/baker/ProtoEventAdapterSpec.scala
Adding test for the types to and from protobuf.
=> Adding tests for protobuf 

runtime/src/main/scala/com/ing/baker/runtime/actor/GracefulShutdown.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/GracefulShutdownShardRegions.scala, runtime/src/main/scala/com/ing/baker/runtime/actor/Util.scala, runtime/src/main/scala/com/ing/baker/runtime/core/Baker.scala, runtime/src/main/scala/com/ing/baker/runtime/java_api/JBaker.scala
- Added more and clearer logging
- Leave the akka cluster synchronously
=> Improved the graceful shutdown procedure

compiler/src/main/scala/com/ing/baker/compiler/RecipeCompiler.scala
Changed when intermediate event input places are created.
They are now only created if there are multiple interactions firing the event.
=> Optimize event incoming intermediate transition

bakertypes/src/main/scala/com/ing/baker/types/Value.scala, bakertypes/src/main/scala/com/ing/baker/types/modules/JavaModules.scala, bakertypes/src/test/scala/com/ing/baker/types/modules/JavaModulesSpec.scala
=> generics support: asList, asSet, asMap in value conversions to java collection types

docs/feature-comparison.md
Answering questions from enterprise architects.
=> Baker feature comparison

CHANGELOG.md, runtime/src/test/scala/com/ing/baker/runtime/core/BakerExecutionSpec.scala
Release notes for Release 2.0.4
=> Release 2.0.4

baas/src/main/protobuf/baas.proto, baas/src/main/scala/com/ing/baker/baas/interaction/client/RemoteInteractionClient.scala, baas/src/main/scala/com/ing/baker/baas/interaction/server/RemoteInteractionLauncher.scala, baas/src/main/scala/com/ing/baker/baas/server/protocol/AddInteractionHTTPRequest.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/internal/InteractionManager.scala, runtime/src/main/scala/com/ing/baker/runtime/common/InteractionInstance.scala, runtime/src/main/scala/com/ing/baker/runtime/javadsl/InteractionInstance.scala, runtime/src/main/scala/com/ing/baker/runtime/scaladsl/InteractionInstance.scala, runtime/src/test/scala/com/ing/baker/runtime/ScalaDSLRuntime.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/BakerExecutionSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/internal/InteractionManagerSpec.scala
=> Changed InteractionInstance.input to a Seq[Type]

baas/src/main/scala/com/ing/baker/baas/client/BaasBaker.scala, baas/src/main/scala/com/ing/baker/baas/server/BaasRoutes.scala, baas/src/main/scala/com/ing/baker/baas/server/protocol/BakeResponse.scala, baas/src/main/scala/com/ing/baker/baas/server/protocol/StateResponse.scala, baas/src/main/scala/com/ing/baker/baas/util/ClientUtils.scala, baas/src/test/scala/com/ing/baker/baas/BaasSpec.scala, integration/src/multi-jvm/scala/com/ing/baker/HappyPathSpec.scala, runtime/src/main/resources/reference.conf, runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstance.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/actor/serialization/BakerTypedProtobufSerializer.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/actor/serialization/ProtoMap.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/actor/serialization/protomappings/ProcessStateMapping.scala, runtime/src/main/scala/com/ing/baker/runtime/akka/internal/RecipeRuntime.scala, runtime/src/main/scala/com/ing/baker/runtime/common/Baker.scala, runtime/src/main/scala/com/ing/baker/runtime/common/RecipeInstanceState.scala, runtime/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala, runtime/src/main/scala/com/ing/baker/runtime/javadsl/RecipeInstanceState.scala, runtime/src/main/scala/com/ing/baker/runtime/scaladsl/Baker.scala, runtime/src/main/scala/com/ing/baker/runtime/scaladsl/RecipeInstanceState.scala, runtime/src/test/java/com/ing/baker/BakerTest.java, runtime/src/test/java/com/ing/baker/Webshop.java, runtime/src/test/scala/com/ing/baker/BakerRuntimeTestBase.scala, runtime/src/test/scala/com/ing/baker/runtime/ExamplesSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/BakerExecutionSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/BakerSetupSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndexSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/serialization/SerializationSpec.scala
…to their corresponding baker 3.0 namings
=> Renamed getProcessState, addImplementation and getAllProcessMetadata

docs/index.md, docs/sections/concepts.md, docs/sections/development-life-cycle/bake-fire-events-and-inquiry.md, docs/sections/development-life-cycle/design-a-recipe.md, docs/sections/development-life-cycle/use-visualizations.md, docs/sections/getting-started.md, docs/sections/reference/dsls.md, docs/sections/reference/event-listener.md, docs/sections/reference/execution-semantics.md, docs/sections/reference/main-abstractions.md
=> Fix broken links in the documentation

docs/sections/getting-started.md
=> Documentation MAVEN dependency fixed

docs/archive/getting-started.md, docs/sections/getting-started.md
=> Fix for maven Dependency documentation

bakertypes/src/test/scala/com/ing/baker/types/modules/JodaTimeModuleSpec.scala, bakertypes/src/test/scala/com/ing/baker/types/modules/PrimitiveModuleSpec.scala, bakertypes/src/test/scala/com/ing/baker/types/modules/ScalaModulesSpec.scala, intermediate-language/src/test/scala/com/ing/baker/il/HashcodeGenerationSpec.scala, project/Dependencies.scala, recipe-dsl/src/test/scala/com/ing/baker/recipe/common/HashingSpec.scala, runtime/src/test/scala/com/ing/baker/BakerRuntimeTestBase.scala, runtime/src/test/scala/com/ing/baker/pbt/RecipePropertiesSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndexSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/serialization/EncryptionPropertiesSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/actor/serialization/SerializationSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/internal/InteractionManagerSpec.scala, runtime/src/test/scala/com/ing/baker/runtime/akka/internal/RecipeRuntimeSpec.scala
Updates org.scalatest:scalatest from 3.0.5 to 3.0.8.
=> Update scalatest to 3.0.8

README.md, docs/archive/presentations/baker-pitch.md
Added a reference to the workshop that Tim and I used last week to facilitate a group of Java developers learning about Baker.
=> Workshop readme

project/Dependencies.scala, project/build.properties, project/plugins.sbt
=> bundled version bumps

bakery-controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/BakerController.scala, bakery-controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/InteractionController.scala
let operator copy source labels when making derived resources
=> copying labels

azure.yaml
code coverage report - in a separate step, and only on master branch
=> remove instrumented code

azure.yaml
wrong expression, can't test in other branch than master
=> fix condition pipeline

baas-node-state/src/main/scala/com/ing/baker/baas/state/ServiceDiscovery.scala, baas-node-state/src/test/scala/com/ing/baker/baas/mocks/KubeApiServer.scala, baas-smoke-tests/src/test/resources/kubernetes/example-client-app.yaml, baas-smoke-tests/src/test/scala/com/ing/baker/baas/smoke/BakeryEnvironment.scala, bakery-controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/BakerController.scala, bakery-controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/InteractionController.scala, bakery-controller/src/test/scala/com/ing/bakery/clustercontroller/BakeryControllerSpec.scala
=> refactored labels

bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala, bakery/baker/src/main/scala/com/ing/bakery/baker/BakerService.scala, bakery/baker/src/test/scala/com/ing/bakery/baker/BakerNodeSpec.scala
added validation of path parameters - recipe id, recipe instance id, interaction name
=> path parameter validation

bakery-integration-tests/src/test/resources/kubernetes/configmap/baker-webshop-update-recipes.yaml, bakery-integration-tests/src/test/resources/kubernetes/configmap/baker-webshop.yaml, bakery-integration-tests/src/test/resources/kubernetes/configmap/interactions-example.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/baker-webshop-update-recipes.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/baker-webshop.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/interactions-example.yaml, bakery/baker/src/main/resources/reference.conf, bakery/baker/src/main/scala/com/ing/bakery/baker/Main.scala, bakery/baker/src/main/scala/com/ing/bakery/baker/ServiceDiscovery.scala, bakery/baker/src/test/scala/com/ing/bakery/baker/BakerNodeSpec.scala, bakery/baker/src/test/scala/com/ing/bakery/mocks/KubeApiServer.scala, bakery/controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/BakerController.scala, bakery/controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/InteractionController.scala
added scope labels for baker interaction discovery
=> scope labels for baker interaction discovery

bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala, bakery/baker-client/src/test/scala/com/ing/bakery/client/BakerClientSpec.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala
=> Make Baker AutoCloseable for try-catch sugar from Java interface

.bsp/sbt.json, .gitignore, bakery/baker-client/src/main/resources/reference.conf, bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverUtils.scala, bakery/baker-client/src/test/scala/com/ing/bakery/common/FailoverUtilsSpec.scala
1. Improve failover logging
2. Introduce configuration params for failover
3. Remove bsp from repository
=> Improve failover utils

azure-build.yaml, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/SensoryEventResponseHandler.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstance.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/AkkaTestBase.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/SensoryEventResponseHandlerSpec.scala, project/Dependencies.scala, project/plugins.sbt
- added receivetimeout cleanup for idle timeout failures
- bumped deps versions
- metrics for SensoryEventResponseHandler
=> idle timeouts

bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverState.scala, bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverUtils.scala, bakery/baker-client/src/main/scala/com/ing/bakery/javadsl/BakerClient.scala, bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala, bakery/baker-client/src/test/scala/com/ing/bakery/client/BakerClientSpec.scala, bakery/baker-client/src/test/scala/com/ing/bakery/common/FailoverStateSpec.scala, bakery/baker-client/src/test/scala/com/ing/bakery/common/FailoverUtilsSpec.scala, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/BakerService.scala, bakery/baker-unified/src/test/scala/com/ing/bakery/baker/StateRuntimeSpec.scala, bakery/baker/src/main/scala/com/ing/bakery/baker/ServiceDiscovery.scala, bakery/interaction-spring/src/main/scala/com/ing/bakery/interaction/spring/Main.scala, bakery/interaction-spring/src/test/scala/com/ing/bakery/interaction/spring/MainTest.scala, bakery/interaction-spring/src/test/scala/com/ing/bakery/interaction/spring/TestConfiguration.scala, bakery/interaction-spring/src/test/scala/com/ing/bakery/interaction/spring/TestConfiguration2.scala, bakery/interaction-spring/src/test/scala/com/ing/bakery/interaction/spring/TestInteraction.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/PollingAware.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/BakerSetupSpec.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryInteractions.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/model/InteractionsF.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/model/RecipeManager.scala, core/baker-interface/src/test/scala/com/ing/baker/runtime/inmemory/InMemoryBakerSpec.scala, core/baker-interface/src/test/scala/com/ing/baker/runtime/model/BakerModelSpecSetupTests.scala, project/Dependencies.scala
support multiple spring contexts for launching interactions
=> support multiple spring contexts for launching interactions

bakery/baker-client/src/main/scala/com/ing/bakery/common/FailoverUtils.scala, bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala, bakery/baker-unified/src/test/scala/com/ing/bakery/baker/StateRuntimeSpec.scala, bakery/baker/src/test/scala/com/ing/bakery/baker/BakerNodeSpec.scala
Fixed the 404 errors for the FailOverUtils client.
=> Fixed the 404 errors for the FailOverUtils client.

bakery-integration-tests/src/test/resources/kubernetes/crd/crd-baker.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/crd-interaction.yaml, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/BakerService.scala, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/InteractionDiscovery.scala, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/Main.scala, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/RecipeLoader.scala, bakery/interaction-protocol/src/main/scala/com/ing/bakery/interaction/RemoteInteractionClient.scala, bakery/interaction/src/main/scala/com/ing/bakery/interaction/RemoteInteractionService.scala
k8s lazy init, logging/metric fixes
=> k8s lazy init, logging fixes

bakery/baker-client/src/main/scala/com/ing/bakery/scaladsl/BakerClient.scala, bakery/baker-unified/src/main/scala/com/ing/bakery/baker/BakerService.scala, bakery/baker-unified/src/test/scala/com/ing/bakery/baker/StateRuntimeSpec.scala, bakery/baker-unified/src/test/scala/com/ing/bakery/mocks/RemoteInteraction.scala, bakery/baker/src/main/scala/com/ing/bakery/baker/ServiceDiscovery.scala, bakery/baker/src/test/scala/com/ing/bakery/baker/BakerNodeSpec.scala, bakery/baker/src/test/scala/com/ing/bakery/mocks/KubeApiServer.scala, bakery/baker/src/test/scala/com/ing/bakery/mocks/RemoteInteraction.scala, bakery/controller/src/main/scala/com/ing/bakery/clustercontroller/controllers/InteractionController.scala, bakery/controller/src/test/scala/com/ing/bakery/mocks/KubeApiServer.scala, bakery/controller/src/test/scala/com/ing/bakery/mocks/RemoteInteraction.scala, bakery/interaction-protocol/src/main/scala/com/ing/bakery/interaction/RemoteInteractionClient.scala, bakery/interaction-protocol/src/main/scala/com/ing/bakery/protocol/InteractionExecution.scala, bakery/interaction/src/main/scala/com/ing/bakery/interaction/RemoteInteractionService.scala, bakery/interaction/src/test/scala/com/ing/bakery/interaction/RemoteInteractionSpec.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/PollingAware.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/common/Baker.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/model/BakerF.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/scaladsl/InteractionInstanceF.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/InteractionExecution.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/JsonDecoders.scala
=> exposes interaction API 

azure-build.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/crd-baker.yaml, bakery-integration-tests/src/test/resources/kubernetes/crd/crd-interaction.yaml, build.sbt, core/akka-runtime/src/main/scala/com/ing/baker/runtime/PollingAware.scala, project/Dependencies.scala, project/scalapb.sbt
=> bump versions & fix CRDs

bakery-integration-tests/src/test/resources/kubernetes/unified/webshop-baker.yaml, bakery/baker-unified/src/test/resources/application.conf, core/akka-runtime/src/main/scala/com/ing/baker/runtime/PollingAware.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/ClusterBakerActorProvider.scala, version.sbt
=> moved cluster init point

bakery/dashboard/src/app/app-routing.module.ts, bakery/dashboard/src/app/instances/instances.component.ts, bakery/dashboard/src/app/notfound/notfound.component.html, bakery/dashboard/src/app/notfound/notfound.component.ts, bakery/dashboard/src/app/notfound/notfound.css, bakery/dashboard/src/app/recipes/recipes.component.ts, bakery/dashboard/src/assets/settings/settings.json
=> More restful dashboard

core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala
doesn't fail when there's no recipe
=> robust process index

core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala
Fixed the java dsl by adding the addRecipe directly to the javaDsl to ensure java understand the typing.
=> Fixed the java dsl by adding the addRecipe directly to the javaDsl 

build.sbt, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/BakerExecutionSpec.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryBaker.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryRecipeInstanceManager.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryRecipeManager.scala, core/baker-interface/src/test/scala/com/ing/baker/runtime/inmemory/InMemoryMemoryCleanupSpec.scala, project/Dependencies.scala
This ensure the memory will not keep filling indefinilty.
=> Added a CacheBuilder as the Map for the in memory RecipeInstanceManager.

project/Dependencies.scala
=> Upgraded the guava version.

bakery/state/src/main/scala/com/ing/bakery/baker/RecipeLoader.scala
This reverts commit 75a02e156b451ecbaff5d0d5ee3be463e2914ec3.
=> Revert "logging loading"

bakery/state/src/main/scala/com/ing/bakery/baker/InteractionRegistry.scala
Fix classnotfound when class is empty
=> Fix issue when interactions.class = ""

build.sbt
Update build.sbt file so that IntelliJ can parse/understand the project and it loads without errors.
Unit tests all succeed.
=> Update build.sbt file so that IntelliJ can parse/understand the project

build.sbt, project/Dependencies.scala, project/build.properties, project/plugins.sbt, project/scalapb.sbt
The ones left are mostly cats-effect related.
=> Updated dependencies found by scala-steward which did not fail CI build.

bakery/dashboard/package.json, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndexSpec.scala
Changed the ProcessIndex to not load all recipes but only the ones that are needed
=> Changed the ProcessIndex to not load all recipes

docs/sections/development-life-cycle/test.md
Adding info about baker-test to official baker documentation.
=> BakerTest documentation

project/Dependencies.scala
updated http4s version to deal with cve
=> updated http4sVersion to 0.21.34

core/akka-runtime/src/main/resources/reference.conf, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBakerConfig.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/ClusterBakerActorProvider.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/LocalBakerActorProvider.scala, core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndexSpec.scala
Added an optional blacklist on startup that deletes processes and not start them.
=> Changed the delete method to not start the Actor if it is not running.

core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryBaker.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryRecipeInstanceManager.scala, core/baker-interface/src/main/scala/com/ing/baker/runtime/model/RecipeInstanceManager.scala, core/baker-interface/src/test/scala/com/ing/baker/runtime/inmemory/InMemoryMemoryCleanupSpec.scala, core/recipe-dsl/src/main/scala/com/ing/baker/recipe/common/InteractionDescriptor.scala, http/baker-http-dashboard/package.json
Improvements to the InMemoryRecipeInstanceManager to not passivate processes that are executing unless that RetentionPeriod expired.
=> Improvements to the InMemoryRecipeInstanceManager passivation

core/baker-interface/src/main/scala/com/ing/baker/runtime/inmemory/InMemoryRecipeInstanceManager.scala, core/baker-interface/src/test/scala/com/ing/baker/runtime/inmemory/InMemoryMemoryCleanupSpec.scala
=> Fix inmemory last updated

docs/sections/cookbook/recipe-dsl.md, examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeWithRetentionPeriod.java, examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeWithRetentionPeriod.kt, examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeWithRetentionPeriod.scala
Added a section on Recipe retention
=> Added a section on Recipe Retention period to the docs

examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeWithRetentionPeriod.java, examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeWithRetentionPeriod.kt, examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeWithRetentionPeriod.scala
Also changed some class names to match example and filename
=> Added some missing imports

core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstance.scala, core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceSpec.scala
Fixed the Wait interaction to work if you also have a retry strategy that fires and event.
=> Fixed the Wait interaction to work if you also have a retry strategy that fires and event.

.gitignore, build.sbt, core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala, project/build.properties, project/plugins.sbt
chore: Update sbt plugins to latest versions
chore: Update scala version to 2.13.14
chore: Update sbt version to 1.10.1
chore: Remove unnecessary code in Baker.scala
chore: gitignore gitconfig file
=> Sbt and scala library upgrade

core/baker-interface/src/main/scala/com/ing/baker/runtime/model/InteractionInstance.scala
Fixed the interactionId for the InteractionInstance to ensure this is unique if output is different
=> Fixed the interactionId for the InteractionInstance

http/baker-http-server/src/main/scala/com/ing/baker/http/server/javadsl/BakerWithHttpResponse.scala
Exposed the parseEventRequest method to the deserialisation so it can be reused
=> Exposed the parseEventRequest method to the deserialisation so it can be reused

core/akka-runtime/src/test/scala/com/ing/baker/AllTypeRecipe.scala, core/recipe-compiler/src/test/scala/com/ing/baker/compiler/RecipeCompilerSpec.scala, core/recipe-dsl-kotlin/src/main/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDsl.kt, core/recipe-dsl/src/main/scala/com/ing/baker/recipe/common/InteractionFailureStrategy.scala, core/recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/InteractionFailureStrategy.scala, docs/sections/cookbook/error-handling.md, examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeFireEventAndBlock.java, examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeFireEventAndResolve.java, examples/docs-code-snippets/src/main/java/examples/java/recipes/RecipeRetryWithBackOfWithFireEventAndBlock.java, examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeFireEventAndBlock.kt, examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeFireEventAndResolve.kt, examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeRetryWithBackOfWithFireEventAndBlock.kt, examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeFireEventAndBlock.scala, examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeFireEventAndResolve.scala, examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeRetryWithBackOfWithFireEventAndBlock.scala
Added missing fireEventAndBlock and FireEventAndResolve methods towards the DSL and updated the docs with the new strategies.
=> Added missing fireEventAndBlock and FireEventAndResolve methods
